name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.MYPASS }}" | docker login -u "rjrohitshaw" --password-stdin
        docker image build -t rjrohitshaw/pyflask:latest .
        docker push rjrohitshaw/pyflask:latest